export const ECOSYSTEM_CATALOG_VERSION = "2026-09-02e";
export const ECOSYSTEM_REVIEWED_AT = "2026-09-01T04:00:00Z";

// This directory contains only source-reviewed public material. Source tier, author,
// original language, URL and risk boundary are evidence fields and must not be inferred
// from translated copy or user-submitted claims.
export const CURATED_UPDATES = Object.freeze([
  {
    id: "official-alpha-demo",
    source_type: "x_post",
    tier: "official",
    author: "@Blonskr",
    url: "https://x.com/Blonskr/status/2088639148660076696",
    original_language: "en",
    topics: ["canvas", "tapeout", "design"],
    published_at: null,
    reviewed_at: "2026-08-25T06:30:00Z",
    title_en: "Alpha launch demo: Canvas, tape-out and examples",
    title_zh: "Alpha 上线演示：画布、流片与示例规模",
    summary_en: "Official public launch material demonstrating the basic path from NAND/LATCH and Canvas wiring to tape-out. Use it to understand the workflow, not as a return forecast.",
    summary_zh: "官方公开发布，用 NAND/LATCH、Canvas 连线和示例说明从设计到流片的基本路径；用于理解工作流，不构成收益预期。",
    source_note_en: "Official project release. Verify the linked account and any contract address on the official site before signing.",
    source_note_zh: "官方项目公开发布。签名前仍应在官网核验账号与任何合约地址。",
    risk_tags: ["verify-contract", "irreversible-transaction", "no-return-promise"]
  },
  {
    id: "official-output-cost-note",
    source_type: "x_post",
    tier: "official",
    author: "@Blonskr",
    url: "https://x.com/Blonskr/status/2090510180979278026",
    original_language: "en",
    topics: ["canvas", "cost", "safety"],
    published_at: null,
    reviewed_at: "2026-08-25T06:30:00Z",
    title_en: "Output-pin cost and netlist rule note",
    title_zh: "输出引脚成本与网表规则说明",
    summary_en: "Official explanation of why Canvas gate count can differ from final tape-out consumption. Check inputs, outputs and cost before signing a transaction.",
    summary_zh: "官方说明为什么 Canvas 上的门数可能不同于最终流片消耗；签名前应核对输入、输出与成本。",
    source_note_en: "Official project release. Cost information is a protocol-mechanics reference, not a valuation or return claim.",
    source_note_zh: "官方项目公开发布。成本信息用于理解协议机制，不是估值或收益声明。",
    risk_tags: ["verify-cost", "irreversible-transaction", "no-return-promise"]
  },
  {
    id: "community-beginner-guide",
    source_type: "x_article",
    tier: "community",
    author: "@blueshirt666",
    url: "https://x.com/blueshirt666/article/2089678489373004233",
    original_language: "en",
    topics: ["tutorial", "verification", "safety"],
    published_at: "2026-08-18T07:32:04Z",
    reviewed_at: "2026-08-25T06:30:00Z",
    title_en: "From Mint to Tape-out: a beginner’s guide to TapeOut",
    title_zh: "从 Mint 到 Tape-out：TapeOut 新手指南",
    summary_en: "Community beginner guide covering isolated-wallet testing, read-only contract checks and irreversible tape-out risks. Official sources remain authoritative for mechanics.",
    summary_zh: "社区新手教程，涵盖隔离钱包测试、只读合约核验与不可逆流片风险；协议机制仍以官方来源为准。",
    source_note_en: "Community content, never an official source. The article includes a risk disclosure; independently verify mechanics and contracts.",
    source_note_zh: "社区内容，绝非官方来源。文章含风险披露；仍需独立核验机制与合约。",
    risk_tags: ["community-not-official", "read-only-first", "no-return-promise"]
  },
  {
    id: "official-pod-entry",
    source_type: "official_site",
    tier: "official",
    author: "TapeOut Protocol",
    url: "https://tapeout.net/pod/",
    original_language: "en",
    topics: ["pod", "taskbank", "safety"],
    published_at: null,
    reviewed_at: "2026-08-25T06:30:00Z",
    title_en: "$BEM Proof of Design: official mining entry",
    title_zh: "$BEM Proof of Design：官方挖矿入口",
    summary_en: "Official entry for arm, start, claim, taskbank and contracts. It discloses irreversible transactions and that buying tokens is not required.",
    summary_zh: "官方 arm、start、claim、题库和合约入口；页面披露交易不可逆且无需买币。",
    source_note_en: "Official site source. Treat any third-party price or mining discussion separately from the official rule page.",
    source_note_zh: "官方站点来源。任何第三方价格或挖矿讨论都应与官方规则页面分开看待。",
    risk_tags: ["official-rules", "irreversible-transaction", "third-party-price-not-official"]
  },
  {
    id: "community-web3kexin-intro",
    source_type: "x_post",
    tier: "community",
    author: "@web3kexin",
    url: "https://x.com/web3kexin/status/2092907816545841435",
    original_language: "zh",
    topics: ["basics", "logic", "value-chain"],
    published_at: null,
    reviewed_at: "2026-08-27T15:55:00Z",
    title_en: "One article to understand TapeOut",
    title_zh: "一篇文章带你了解 TapeOut",
    summary_en: "Community explainer walking through the NAND/LATCH -> Circuit -> hashpower -> BEM value chain and the difference between TapeOut and Behemoth transistors. Conceptual framing only, no price or return claims.",
    summary_zh: "社区科普长文，梳理 NAND/LATCH → Circuit → 算力 → BEM 的价值传导链条，并说明 TapeOut 与 Behemoth 晶体管的区别；仅为概念性框架，不含价格或收益话术。",
    source_note_en: "Community content, never an official source. Mechanics should still be cross-checked against the official site.",
    source_note_zh: "社区内容，绝非官方来源。机制仍应与官网核对。",
    risk_tags: ["community-not-official", "no-return-promise"]
  },
  {
    id: "community-ranynft-v2-supplychain",
    source_type: "x_post",
    tier: "community",
    author: "@ranynft",
    url: "https://x.com/ranynft/status/2092882194134127073",
    original_language: "zh",
    topics: ["architecture", "pod", "analysis"],
    published_at: null,
    reviewed_at: "2026-08-27T15:55:00Z",
    title_en: "TapeOut V2: an on-chain analogy for the AI compute hardware supply chain",
    title_zh: "TapeOut V2：把“AI 算力硬件产业链”搬上链",
    summary_en: "Community analysis mapping Processor/Circuit/PoD to an upstream-midstream-downstream hardware-industry analogy, and restating the public H = (burned cost + design premium) x processor-coefficient weighting in plain terms. Uses hedged language throughout and does not forecast returns.",
    summary_zh: "社区分析文章，把 Processor/Circuit/PoD 类比为硬件产业链的上中下游，并用通俗语言复述公开的 H ≈（烧毁工本+设计溢价）×处理器系数 权重公式；全文使用限定性表述，不做收益预测。",
    source_note_en: "Community content, never an official source. Treat the industry analogy as an explanatory device, not an official architecture claim.",
    source_note_zh: "社区内容，绝非官方来源。产业链类比是解释性工具，不是官方架构声明。",
    risk_tags: ["community-not-official", "no-return-promise"]
  },
  {
    id: "community-lilmxgma-beginner-guide",
    source_type: "x_post",
    tier: "community",
    author: "@lilmxgma",
    url: "https://x.com/lilmxgma/status/2092286231015260395",
    original_language: "zh",
    topics: ["tutorial", "wallet-safety", "verification"],
    published_at: null,
    reviewed_at: "2026-08-27T15:55:00Z",
    title_en: "TapeOut beginner's guide: build your first circuit from zero",
    title_zh: "TapeOut 新手指南：从零开始，在链上搭出你的第一个电路",
    summary_en: "Community beginner guide covering NAND/LATCH basics, an isolated experimental-wallet recommendation, the official-contract-upgradeability disclosure, and an explicit distinction between the official site and unofficial community tools. Includes a risk warning before every signing step.",
    summary_zh: "社区新手教程，讲解 NAND/LATCH 基础、建议使用隔离实验钱包、披露官方合约仍处于可升级阶段、并明确区分官网与非官方社区工具；每个签名步骤前都附风险提示。",
    source_note_en: "Community content, never an official source. The guide's own safety warnings are a strong signal of quality but do not replace independent verification.",
    source_note_zh: "社区内容，绝非官方来源。文中的安全提示质量较高，但不能替代独立核验。",
    risk_tags: ["community-not-official", "read-only-first", "no-return-promise"]
  },
  {
    id: "official-pod-counterexample-review",
    source_type: "x_post",
    tier: "official",
    author: "@Blonskr",
    url: "https://x.com/Blonskr/status/2094644591425401189",
    original_language: "zh",
    topics: ["pod", "verification", "protocol-change"],
    published_at: "2026-09-01T04:32:41Z",
    reviewed_at: "2026-09-02T16:40:00Z",
    title_en: "PoD adds counterexample review: anyone can challenge a circuit that only fits the sampled vectors",
    title_zh: "PoD 新增反例审查：任何人可挑战只拟合抽检点的电路",
    summary_en: "Founder's announcement of a protocol change queued on-chain with a 48-hour delay and stated to take effect at 2026-09-02 16:14:50 UTC. The post states that mining currently spot-checks only 3 to 32 official vectors per circuit, that an exhaustive check of the 534 top-ranked slots found 80 circuits which pass the spot check but differ from the reference over the full input space (13.99% of verified-pool weight), and that after the upgrade anyone can submit a counterexample: if the challenged circuit fails it, its design premium is withdrawn automatically; an honest miner is unaffected. Two implementation contract addresses and a proposal hash are given in the post. When this entry was reviewed, shortly after the stated activation time, the official PoD page did not yet describe the mechanism.",
    summary_zh: "创始人宣布的一项协议变更：已提交上链排队、48 小时延迟，声明于 2026-09-02 16:14:50 UTC 生效。原帖称，目前电路挖矿只对每个电路抽检 3~32 条官方向量；对 534 个最优槽逐条穷举后发现 80 个电路能通过抽检、却在全输入空间上与参考实现不符（占已验证池权重 13.99%）；升级后任何人都能提交一条反例，被挑战的电路若通不过，其设计溢价将被系统自动撤回，诚实矿工不受影响。帖中给出了两个实现合约地址和一个提案哈希。本条目审核时（声明生效时间刚过），官方 PoD 页面尚未描述这一机制。",
    source_note_en: "Official founder post. The 3–32 vector figure, the 80-of-534 count and the 13.99% weight share are the post's own statements, not independently reproduced here; verify the two contract addresses and the proposal hash on-chain before relying on them.",
    source_note_zh: "官方创始人原帖。3~32 条向量、534 中的 80 个、13.99% 权重占比均为原帖自述，本站未独立复现；依赖前请在链上核验帖中两个合约地址与提案哈希。",
    risk_tags: ["official-rules", "verify-contract", "protocol-change"]
  }
]);

export const CURATED_TOOLS = Object.freeze([
  {
    id: "tool-tapeout-canvas",
    wallet_risk: "connects_wallet",
    category: "design",
    tier: "official",
    operator: "TapeOut Protocol",
    url: "https://tapeout.net/",
    original_language: "en",
    reviewed_at: "2026-08-25T06:30:00Z",
    title_en: "TapeOut Canvas",
    title_zh: "TapeOut Canvas 设计画布",
    summary_en: "Official browser workspace for building and testing NAND/LATCH circuit logic before any tape-out transaction.",
    summary_zh: "官方浏览器工作区，用于在任何流片交易前搭建并测试 NAND/LATCH 电路逻辑。",
    use_cases: ["design", "test"],
    safety_en: "Test first. Tape-out can create an irreversible on-chain transaction; verify displayed inputs, outputs, components and cost before signing.",
    safety_zh: "先测试。流片可能创建不可逆的链上交易；签名前核对输入、输出、元件和成本。"
  },
  {
    id: "tool-pod",
    wallet_risk: "connects_wallet",
    category: "proof_of_design",
    tier: "official",
    operator: "TapeOut Protocol",
    url: "https://tapeout.net/pod/",
    original_language: "en",
    reviewed_at: "2026-08-25T06:30:00Z",
    title_en: "$BEM Proof of Design",
    title_zh: "$BEM Proof of Design",
    summary_en: "Official PoD entry for rule reading, arm/start/claim workflow, mining status and contract references.",
    summary_zh: "官方 PoD 入口，用于阅读规则、执行 arm/start/claim 流程、查看挖矿状态和合约引用。",
    use_cases: ["pod", "rules", "contract-reference"],
    safety_en: "Use official rule and contract references only. Transactions are irreversible; this is not a promise of mining returns.",
    safety_zh: "仅使用官方规则和合约引用。交易不可逆；这不构成挖矿收益承诺。"
  },
  {
    id: "tool-pod-taskbank",
    wallet_risk: "read_only",
    category: "learning",
    tier: "official",
    operator: "TapeOut Protocol",
    url: "https://tapeout.net/pod/#pod-tasks",
    original_language: "en",
    reviewed_at: "2026-08-25T06:30:00Z",
    title_en: "PoD taskbank",
    title_zh: "PoD 官方题库",
    summary_en: "Official task catalog for selecting exercises by tier, combinational/sequential type and on-chain eligibility.",
    summary_zh: "官方题目目录，可按难度、组合/时序类型和上链资格选择练习。",
    use_cases: ["learning", "pod", "task-selection"],
    safety_en: "Read verification requirements before any claim. A task label does not guarantee a reward or token value.",
    safety_zh: "任何认领前先阅读验证要求。题目标签不保证奖励或代币价值。"
  },
  {
    id: "tool-bscscan-pod",
    wallet_risk: "read_only",
    category: "verification",
    tier: "reference",
    operator: "BscScan",
    url: "https://bscscan.com/address/0x7E2E0DC66a3bD9103E69b766afA62d9f7b697b46",
    original_language: "en",
    reviewed_at: "2026-08-25T06:30:00Z",
    title_en: "BscScan read-only PoD contract check",
    title_zh: "BscScan PoD 合约只读核验",
    summary_en: "Read-only explorer page for cross-checking the public PoD contract address and transaction state against official references.",
    summary_zh: "只读浏览器页面，用于对照官方引用核验公开 PoD 合约地址和交易状态。",
    use_cases: ["verification", "read-only", "contract-check"],
    safety_en: "A block explorer is not an audit or a return metric. Do not treat any copied address as trusted without matching it to the official source.",
    safety_zh: "区块浏览器不是审计结论或收益指标。任何复制的地址都必须先与官方来源匹配。"
  },
  {
    id: "tool-tapeout-club",
    wallet_risk: "read_only",
    category: "hashpower_analytics",
    tier: "community",
    operator: "TapeOut Club",
    url: "https://tapeout.club/",
    original_language: "zh",
    reviewed_at: "2026-08-25T10:45:00Z",
    title_en: "TapeOut Club processor & hashpower board",
    title_zh: "TapeOut Club 处理器与算力榜",
    summary_en: "Community-facing public board for processor and hashpower observations. Its calculations are useful as a separate ecosystem view, but are not an official holder or protocol source.",
    summary_zh: "面向社区的公开处理器与算力观察面板。其计算可作为独立生态视角，但不是官方 holder 或协议事实来源。",
    use_cases: ["hashpower", "processor-observation", "community-estimate"],
    safety_en: "Community estimate only. Treat ranking coverage, projected outputs and labels as source-specific observations; do not infer current wallet balances, identities or guaranteed returns.",
    safety_zh: "仅为社区推算。榜单覆盖、预计产出和标签均是来源特定观察；不可推断当前钱包余额、真实身份或保证回报。"
  },
  {
    id: "tool-tapeout-firsto",
    wallet_risk: "connects_wallet",
    category: "marketplace",
    tier: "community",
    operator: "Firsto",
    url: "https://tapeout.firsto.ai/",
    original_language: "zh",
    reviewed_at: "2026-09-02T02:11:46Z",
    title_en: "TapeOut Firsto marketplace",
    title_zh: "TapeOut Firsto 晶体管与矿机市场",
    summary_en: "Third-party ecosystem trading surface for TapeOut-related transistor and mining-machine listings, presenting itself as a professional trading terminal rather than a listings board. Behind the landing page it serves a live per-fill trade tape: every fill shows buy or sell direction, total BNB, quantity, unit price, the counterparty wallet and a BscScan transaction link, running hours deep. Scope note: that tape was the only surface this review could retrieve — no navigation and no other sections came back — so this describes what the interior shows, not the full extent of what the site offers. Use it as a discovery and market-reading surface, separate from official protocol and ownership data.",
    summary_zh: "第三方生态交易入口，展示 TapeOut 相关晶体管与矿机条目，自我定位为「专业交易终端」而非单纯的挂单板。落地页之后确实提供一条实时逐笔成交流水：每一笔都给出买入/卖出方向、总 BNB、数量、单价、对手方钱包，以及一个 BscScan 交易链接，可回溯数小时。范围说明：本次审核只取回了这一个界面，导航和其他板块都没有取回，所以以上写的是内部展示了什么，不代表该站提供的全部内容。可用于发现和阅读市场信息，但应与官方协议和持仓数据分开看待。",
    use_cases: ["market-discovery", "listing-reading", "ecosystem"],
    safety_en: "Community marketplace, not an official price or ownership source. Listings, displayed prices and availability can change and do not guarantee execution; verify contracts and signing requests independently.",
    safety_zh: "社区市场，不是官方价格或持仓来源。挂单、显示价格和可用性会变化，且不保证成交；应独立核验合约与签名请求。"
  },
  {
    id: "tool-tapeout-market",
    wallet_risk: "connects_wallet",
    category: "marketplace",
    tier: "community",
    operator: "TapeOut Market (community)",
    url: "https://tapeout.market/",
    original_language: "en",
    reviewed_at: "2026-09-02T09:02:55Z",
    title_en: "TapeOut Market",
    title_zh: "TapeOut Market 晶体管市场",
    summary_en: "Community ecosystem market whose navigation reaches well past listings. Three sections the name does not suggest: /circuits is a secondary market for taped-out mining machines (Circuit NFTs) which aggregates the official tapeout.net listings alongside its own and labels each card's source so the split stays visible, showing per-machine pending BEM, task ID, hashrate, pool and estimated daily output. /mining is a network dashboard covering halving phase, emission rate and next-halving countdown, active and verified machine counts and hashrate, named price sources (a specific PancakeSwap V3 BEM/USDT pool, with BNB/USD via Chainlink), and a Forgone Emissions counter that no other tool in this catalogue publishes. /create is a four-step wizard over all official tasks with filters and sorting by NAND and LATCH requirement, plus a per-task estimated daily output for both processors computed in the browser. A Tools page adds a Circuit Mining Calculator that reads a circuit's on-chain data, checks it against the compatible official task vectors and estimates verified-pool output and payback. The circuit listings carry the site's own caveat that what it shows is a data cover, not netlist topology. Treat all of it separately from official protocol, contract and ownership sources.",
    summary_zh: "社区生态市场，导航范围远不止挂单。有三块是名字看不出来的：/circuits 是已流片矿机（Circuit NFT）的二级市场，把官方 tapeout.net 的挂单与自家挂单聚合在一起，并逐条标出来源以便区分，每台显示待领 BEM、题目 ID、算力、所属池和预估日产；/mining 是全网仪表盘，涵盖减半阶段、发行速率与下次减半倒计时、活跃与已验证矿机数及算力、明确写出的价格来源（指定的 PancakeSwap V3 BEM/USDT 池，BNB/USD 走 Chainlink），以及一个本目录中其他工具都没有发布的「Forgone Emissions」（未被发行的发行量）计数器；/create 是覆盖全部官方题目的四步向导，可筛选并按 NAND、LATCH 需求排序，还会在浏览器端算出每道题在两种处理器下的预估日产。Tools 页另有一个电路挖矿计算器，读取某台电路的链上数据，对照可匹配的官方题目向量，估算已验证池产出与回本情况。其电路挂单页附有站方自己的限定说明：它展示的是数据封面，不是网表拓扑。以上均应与官方协议、合约和持仓来源分开看待。",
    use_cases: ["market-reading", "orders", "community-market"],
    safety_en: "Community marketplace only. Open bids and displayed values are not completed trades, exit prices or return promises; independently verify current contracts and all wallet requests before signing.",
    safety_zh: "仅为社区市场。公开买单和显示数值不是已成交、退出价格或收益承诺；签名前应独立核验当前合约和全部钱包请求。"
  },
  {
    id: "tool-gatepilot",
    wallet_risk: "connects_wallet",
    category: "mining_rental",
    tier: "community",
    operator: "GatePilot (community)",
    url: "https://tapeout.vibedegens.com/",
    original_language: "zh",
    reviewed_at: "2026-08-28T00:30:00Z",
    title_en: "GatePilot mining & rental platform",
    title_zh: "GatePilot 挖矿·租赁一站式平台",
    summary_en: "Community platform that lets you pick an official taskbank task, generate a reference circuit and .blif file, then either tape out on GatePilot itself or import into the official Canvas; also offers a mining-machine workbench and rental listings. Requires connecting a wallet.",
    summary_zh: "社区平台，可选择官方题库任务生成参考电路与 .blif 文件，再选择在本站直接流片或导入官方画布；同时提供矿机工作台与矿机租赁。需要连接钱包。",
    use_cases: ["reference-circuit", "on-site-tapeout", "mining-workbench", "rental"],
    safety_en: "Third-party platform, not an official TapeOut surface. Connecting a wallet, taping out and renting are all real signable actions with real cost; the generated reference circuit is explicitly \"an ordinary public reference, not a champion design, with no global-optimum proof.\" Verify every contract and signing request independently before approving, and treat rental terms as this platform's own arrangement, not an official protocol feature.",
    safety_zh: "第三方平台，非官方 TapeOut 界面。连接钱包、流片与租赁都是真实可签名、有真实成本的操作；生成的参考电路平台自己说明为\"普通公开参考电路，不代表冠军，也没有全局最优证明\"。批准前应独立核验每一笔合约与签名请求；租赁条款是该平台自身安排，不是官方协议功能。"
  },
  {
    id: "tool-tapeoutgo",
    wallet_risk: "connects_wallet",
    category: "mining_execution",
    tier: "community",
    operator: "0xLukin",
    url: "https://tapeoutgo.vercel.app",
    original_language: "zh",
    reviewed_at: "2026-08-31T00:00:00Z",
    title_en: "TapeOutGo (by 0xLukin)",
    title_zh: "TapeOutGo（作者 0xLukin）",
    summary_en: "The open-source (MIT) tool this site's own \"Budget vs Behemoth\" quote card credits and adapts its read-only pricing methodology from. The original mining flow (buy the shortfall, tape out, arm/start and claim $BEM, all signed directly by your own wallet with no custody) has moved to a \"legacy\" /mine route. The homepage itself now previews a separate, not-yet-launched product from the same author: a \"TapeOut Liquidity Layer\" that would wrap official NAND/LATCH components 1:1 into four fungible tokens (wTapeOutNand/wTapeOutLatch/wBehemothNand/wBehemothLatch) tradeable and poolable against BNB on PancakeSwap, unwrappable anytime at parity. As of this review all four tokens are still marked \"coming soon\" with no deployed contract, so there is nothing live yet to verify or integrate.",
    summary_zh: "本站\"预算对比\"卡片致敬并改编其只读报价方法论的开源（MIT）工具。原本的挖矿流程（买齐差额、流片、逐台 arm/start、领取 $BEM，全程自己钱包签名不经托管）已经移到\"旧版\"的 /mine 路由。首页现在预告了同一作者正在做的另一个尚未上线的产品——\"TapeOut 流动性层\"：把官方 NAND/LATCH 元件按 1:1 包装成四种可流通代币（wTapeOutNand/wTapeOutLatch/wBehemothNand/wBehemothLatch），可在 Pancake 上与 BNB 组成交易对做市，随时可按原比例拆包取回。截至本次审核，四种代币都仍标注\"即将上线\"，尚无已部署的合约，暂时没有可核验或可对接的实际内容。",
    use_cases: ["budget-quote", "buy", "tapeout", "mining", "claim"],
    safety_en: "Community tool, not an official TapeOut surface. Buying, taping out and claiming are real signable, irreversible actions; payback figures exclude gas and are not a return promise. The previewed liquidity-wrapping product is pre-launch — treat any future contract address as unverified until it is actually deployed and independently checked, and note the page's own disclosure that the wrap contract will have no admin key once live (irreversible by design, not upgradable if something goes wrong). Verify every signing request independently.",
    safety_zh: "社区工具，非官方 TapeOut 界面。购买、流片与领取都是真实可签名、不可逆的操作；回本数字不含 gas，也不构成收益承诺。预告中的流动性包装产品尚未上线——在合约真正部署并被独立核实之前，任何未来出现的合约地址都应视为未经验证；页面自己也披露包装合约上线后没有管理员权限（设计上不可逆，出问题也无法升级修复）。每一笔签名请求都应独立核验。"
  },
  {
    id: "tool-intelligence-api",
    drift_profile: "none",
    drift_skip_reason: "this site's own API: its changes are tracked in the repository itself, and the Worker cannot reliably fetch its own hostname",
    wallet_risk: "read_only",
    category: "data",
    tier: "official",
    operator: "TapeOut Intelligence",
    url: "/api/v1/catalog",
    original_language: "en",
    reviewed_at: "2026-08-25T06:30:00Z",
    title_en: "TapeOut Intelligence API",
    title_zh: "TapeOut Intelligence API",
    summary_en: "Public evidence-backed API for Registry, activities, Airdrop, $BEM, reviewed learning resources and multilingual learning responses.",
    summary_zh: "面向 Registry、活动、空投、$BEM、审核学习资源和多语言教学响应的公开证据型 API。",
    use_cases: ["data", "api", "research"],
    safety_en: "Source health, stale state and third-party-price boundaries are part of the response. Do not interpret unavailable data as zero or real time.",
    safety_zh: "来源健康、陈旧状态和第三方价格边界是响应的一部分。不要把不可用数据当作零或实时数据。"
  },
  {
    id: "tool-tapeout-build",
    wallet_risk: "read_only",
    category: "design",
    tier: "community",
    operator: "TapeOut.build (community)",
    url: "https://tapeout.build/",
    original_language: "zh",
    reviewed_at: "2026-09-01T04:00:00Z",
    title_en: "TapeOut.build compute canvas",
    title_zh: "TapeOut.build 算力画布",
    summary_en: "Community-built alternative circuit design canvas: drag NAND/LATCH components, simulate live, and preview an estimated cost breakdown (b*, area A, cost C) before exporting a BLIF file for the official site. Its inspection panel also reports gate and LATCH counts, logic depth, netlist bytes, the auto-matched task spec and the transistor ceiling, and flags dead gates — outputs wired to nothing, which still consume cost and the transistor budget. A prediction panel estimates daily output, share of network and baseline hashpower H excluding any first-creator premium. The decoder accepts a netlist hex string, a transaction hash, a contract address or a pasted tapeout.net/BscScan link.",
    summary_zh: "社区自建的另一款电路设计画布：拖拽 NAND/LATCH 元件、实时仿真，并在导出供官网使用的 BLIF 文件前预览估算的成本分解（b*、面积 A、成本 C）。其检验单还给出门数与 LATCH 数、逻辑深度、网表字节数、自动匹配的题目规格与晶体管上限，并会标出「死门」——输出没有接到任何地方、却照样占用工本与晶体管额度的门。另有产出预测面板，估算日产出、占全网份额与不含首创溢价的保底算力 H。解码功能可接受网表 hex、交易哈希、合约地址，或直接粘贴 tapeout.net / BscScan 链接。",
    use_cases: ["design", "simulation", "export"],
    safety_en: "Community design sandbox, not an official tool. Estimated cost, hashpower and daily-output figures are this site's own preview calculation against the miners currently on chain — the page states plainly that a later tape-out wave will dilute any share it shows — not an official or guaranteed value; only the official Canvas and tape-out transaction are authoritative. Its paid scoring flow (0.001 BNB per run) is currently a demonstration only: the page states this prototype makes no real wallet request, while announcing that the real version will prompt a wallet signature and transfer to a collection address. Treat the read-only classification as true of the prototype as reviewed, not as a guarantee about the shipped version.",
    safety_zh: "社区设计沙盒，非官方工具。预览的成本、算力与日产出数值都是该站基于当前链上已有矿机的自行估算——页面自己也写明后续有更多人流片时你的份额会被摊薄——不是官方或保证值；只有官方 Canvas 与流片交易本身才具有权威性。其付费评分入口（单次 0.001 BNB）目前仅为演示：页面写明本原型不发起真实钱包请求，但同时宣告真实版本会弹出钱包签名并向指定收款地址转账。因此「纯只读」这个判定只对审核当时的原型成立，不构成对正式版本的保证。"
  },
  {
    id: "tool-dune-mining-intelligence",
    drift_profile: "structure", // hosted on a shared platform whose asset builds churn independently of this dashboard
    wallet_risk: "read_only",
    category: "data",
    tier: "community",
    operator: "@ekonomeest (Dune)",
    url: "https://dune.com/ekonomeest/tapeout-mining-intelligence",
    original_language: "en",
    reviewed_at: "2026-09-02T02:42:56Z",
    title_en: "TapeOut Mining Intelligence (Dune)",
    title_zh: "TapeOut Mining Intelligence（Dune 看板）",
    summary_en: "Community-built Dune dashboard with wallet and mining-machine leaderboards across TapeOut and Behemoth, plus live $BEM price, market cap, FDV, primary liquidity, circulating supply and mining-yield figures from on-chain and market data.",
    summary_zh: "社区自建的 Dune 看板，提供覆盖 TapeOut 与 Behemoth 的钱包与矿机排行榜，并聚合链上与市场数据计算的 $BEM 价格、市值、FDV、主要流动性、流通供给与挖矿产出等指标。",
    use_cases: ["analytics", "price-tracking", "community-research"],
    safety_en: "Independent community dashboard, not an official price or protocol source, and deliberately not embedded live on this site: its author can revise it at any time, and a change we have not reviewed should not appear here as though we had checked it. FDV/market-cap figures assume a fixed maximum-supply model; verify methodology on Dune before relying on any number.",
    safety_zh: "独立社区看板，不是官方价格或协议来源，本站也不做实时嵌入，以免作者随时修改而我们未经审核；FDV/市值假设了固定最大供给量模型，使用前应在 Dune 上核实计算口径。"
  },
  {
    id: "tool-tapeout-factory",
    wallet_risk: "connects_wallet",
    category: "mining_execution",
    tier: "community",
    operator: "TapeOut Factory (Benson, community)",
    url: "https://tapeoutfactory.com/",
    original_language: "zh",
    reviewed_at: "2026-09-02T09:02:55Z",
    title_en: "TapeOut Factory (batch tape-out)",
    title_zh: "流片工厂（批量流片）",
    summary_en: "Community batch tape-out tool: pick a published task and its reference-shaped blueprint, then tape out N copies in one flow, each unit still signed and settled as its own wallet transaction. The page discloses upfront when a task's first-creator premium is already claimed by an earlier miner, so a batch run only earns the standard weight, not the originality bonus. It also carries a live BNB/BEM and NAND/LATCH price strip for both processors, a four-step commit-and-sign walkthrough, and a per-task economics table whose columns include estimated daily output, minting cost, hashpower per unit cost, discount to market and static payback days.",
    summary_zh: "社区批量流片工具：选定一道公开题目及其参考形态的图纸，一次流程内连续流片 N 份，但每一份仍是独立的钱包签名与结算交易。页面会提前披露该题目的\"首创加成\"是否已被更早的矿工拿走——若已被拿走，批量流片只能获得普通权重，没有首创加成。站内另有 BNB/BEM 与双处理器 NAND/LATCH 实时价格条、四步「核对题目→承诺→实时终检→签名流片」流程说明，以及一张逐题经济性表格，列包括预计日产、铸造成本、单位成本算力、低于市场价、静态回本天数。",
    use_cases: ["mining", "tapeout", "batch-execution"],
    safety_en: "Community tool, not an official TapeOut surface. Each tape-out in a batch is a real, irreversible, wallet-signed transaction with a real BNB cost; using a shared template means you are not the original designer of that circuit, so no first-creator premium applies if it was already claimed. Verify every signing request independently.",
    safety_zh: "社区工具，非官方 TapeOut 界面。批量中的每一次流片都是真实、不可逆、需要钱包签名并消耗真实 BNB 的交易；使用共用模板意味着你不是该电路的原创设计者，若首创加成已被他人拿走则不会获得。每一笔签名请求都应独立核验。"
  },
  {
    id: "tool-tapeout-verifier",
    wallet_risk: "read_only",
    category: "verification",
    tier: "community",
    operator: "dis404 (community)",
    url: "https://tapeout.pro/",
    original_language: "en",
    reviewed_at: "2026-09-01T20:30:00Z",
    title_en: "tapeout.pro circuit verifier & census",
    title_zh: "tapeout.pro 电路验证器与普查",
    summary_en: "Independent, read-only tool that checks a taped-out circuit against its declared task's on-chain reference implementation over every possible input (or, for sequential tasks, every input/state pair) rather than only the sample vectors the protocol checks. The \"256 fixed, public test vectors\" figure is tapeout.pro's own characterisation of the protocol and is not corroborated by an official page. A second community surface, tapeout.market, does print \"Vector Count 256\" on every task — but that is a community tool as well and could have taken the figure from here, so it is not the official corroboration this caveat is about. What tapeout.market does independently support is the reference-circuit source: it and GatePilot display the same reference-circuit contract address, matching tapeout.pro's account of where the on-chain references live. The protocol side has separately described its sampling as a small number of randomly drawn inputs, and in September 2026 announced a counterexample-review mechanism — network-wide challenges that retract a circuit's design premium — which was not yet documented on the official PoD page when this entry was reviewed. Its Census page publishes a per-miner verdict list with three outcomes, not two: correct, mismatch, and \"correct but padded\" — logic that is equivalent but carries surplus gates, which raise b* and therefore base hashpower. The site notes padding is rational for a miner, costing only the first-creator premium. Census also reports bloat, depth and size against the reference. Reverse-engineered from bytecode since no TapeOut contract is verified on BscScan; the site publishes the rules it recovered, including C = A·d^β and H = (b* + K_task·q)·P.",
    summary_zh: "独立的只读工具，对已流片电路做全输入穷举验算（时序题则做全部输入/状态对），核对是否与其声明题目的官方参考实现真正等价，而不只是通过协议自身抽检的那部分测试向量。其中「256 个固定公开测试向量」是 tapeout.pro 自己对协议的表述，并无官方页面佐证。另有一个社区界面 tapeout.market 确实在每道题上都印着「Vector Count 256」——但它同样是社区工具，这个数字也可能就是从这里取的，因此不构成本条限定语所说的官方佐证。tapeout.market 真正独立印证的是参考电路的来源：它与 GatePilot 显示的参考电路合约地址一致，与 tapeout.pro 所述的链上参考实现存放位置相符。协议方自己的说法是「随机抽取少量输入」，并已于 2026 年 9 月宣告新增「反例审查」机制——由全网提交反例、验证成立则撤回该电路的设计溢价——该机制在本条目审核时尚未出现在官方 PoD 页面上。其 Census 页面的判定**不是两档而是三档**：正确、不匹配，以及「正确但灌水」——逻辑等价但塞了多余的门，从而抬高 b*、进而抬高基础算力；站点自己指出灌水对矿工是理性选择，代价只是拿不到首创溢价。Census 另有灌水程度、深度、尺寸对比参考实现等列。由于官网合约均未在 BscScan 开源验证，其规则是作者从字节码逆向得到的，站点也公开了逆向出的规则，包括 C = A·d^β 与 H = (b* + K_task·q)·P。",
    use_cases: ["verification", "integrity-research", "census"],
    safety_en: "Independent community analysis, not an official or on-chain-enforced verdict. A published \"mismatch\" proves the circuit's logic differs from its declared task over the tested input space; it does not by itself prove intent, and the site says so explicitly. \"Correct but padded\" is likewise a description of a circuit's shape, not an accusation. The recovered formulas are the author's reverse-engineering of unverified bytecode, not an official specification. Read-only — it never asks for a wallet, a signature or a transaction.",
    safety_zh: "独立社区分析，不是官方或链上强制生效的判定。被标记\"不匹配\"只证明该电路逻辑在测试范围内与其声明题目不等价，并不能单独证明是故意作弊——作者本人也这样声明；\"正确但灌水\"同样只是对电路形态的描述，不是指控。其公开的公式是作者对未开源验证字节码的逆向结果，不是官方规范。全站只读，不索取钱包、签名或交易。"
  },
  {
    id: "tool-tapeout-vip",
    wallet_risk: "read_only",
    category: "data",
    tier: "community",
    operator: "GuoBTC (community)",
    url: "https://tapeout.vip/",
    original_language: "zh",
    reviewed_at: "2026-09-01T04:00:00Z",
    title_en: "TapeOut VIP live analytics dashboard",
    title_zh: "TapeOut VIP 实时数据看板",
    summary_en: "Independent trilingual (中/英/한) real-time dashboard: total miners, verified/unverified pool weight, mining progress toward the 21M supply cap, daily emission, BEM price/market cap/FDV, live NAND/LATCH bid-ask for both TapeOut and Behemoth, a per-task \"Rank #1 pioneer\" table, a wallet leaderboard and a hot-task ranking. The task table carries the design shape itself — area, depth and b* as a triple, design cost C, and the first-creator bonus — and the price strip reports the burned share of each transistor type. Reposted approvingly by protocol founder @Blonskr.",
    summary_zh: "独立的中/英/韩三语实时数据看板：矿机总数、已验证/未验证池权重、对齐 2100 万总供给的挖矿进度、日产出、BEM 价格/市值/FDV、TapeOut 与 Behemoth 双边 NAND/LATCH 实时买卖盘、逐题目的\"Rank #1 首创者\"榜单、钱包排行榜与热门题目排名。其题目表直接给出电路形态本身——面积/深度/b* 三元组、设计成本 C、首创加成，价格条还标出每种晶体管的已销毁比例。协议创始人 @Blonskr 曾转发致意。",
    use_cases: ["analytics", "leaderboard", "price-tracking"],
    safety_en: "Independent community dashboard, not an official source. Reviewed directly: the page is read-only and no wallet-connect, signature or transaction prompt was found anywhere on it. Its per-task \"Rank #1\" and weight figures are the author's own computation; verify methodology independently before relying on any number.",
    safety_zh: "独立社区看板，非官方来源。已直接核实：全站只读，未发现任何钱包连接、签名或交易请求。其逐题目\"Rank #1\"与权重数值均为作者自行计算，使用前应独立核实计算口径。"
  },
  {
    id: "tool-bemotc",
    wallet_risk: "connects_wallet",
    category: "marketplace",
    tier: "community",
    operator: "BEM OTC (community)",
    url: "https://bemotc.com/",
    original_language: "zh",
    reviewed_at: "2026-09-02T01:15:00Z",
    title_en: "BEM OTC order-matching market",
    title_zh: "BEM OTC 链上挂单市场",
    summary_en: "Community-built on-chain BEM/USDT peer-to-peer order book on BNB Smart Chain: buyers and sellers post their own price and quantity, funds are locked into the contract at order time, and a trade settles atomically on-chain — intended to fill large orders without moving the thinner AMM pool's price. A 1% fee applies per side.",
    summary_zh: "社区自建的 BNB Smart Chain 上 BEM/USDT 点对点挂单市场：买卖双方自主报价报量，挂单时资产锁入合约，成交由链上原子结算完成——目的是让大额买卖不必直接冲击流动性较浅的 AMM 池价格。双边各收 1% 费率。",
    use_cases: ["otc", "large-order-trading", "price-impact-reduction"],
    safety_en: "Community tool, not an official TapeOut or BEM surface. Requires connecting a wallet inside a dApp browser (MetaMask/OKX/Binance Web3 Wallet/TokenPocket); posting or filling an order is a real, wallet-signed transaction that locks real funds into the contract. The site itself discloses the contract has NOT yet had an independent third-party audit — treat that as an open risk, verify the contract address independently, and only risk amounts you can afford to lose.",
    safety_zh: "社区工具，非官方 TapeOut 或 BEM 界面。需要在 dApp 钱包浏览器（MetaMask/OKX/币安 Web3 钱包/TokenPocket）内连接钱包；挂单或吃单都是真实的钱包签名交易，会把真实资产锁入合约。网站自己披露合约**尚未经过独立第三方审计**——这是一个公开的未消解风险，使用前应独立核实合约地址，且只投入能承受损失的金额。"
  },
  {
    id: "tool-tapeout-index",
    wallet_risk: "read_only",
    category: "navigation",
    tier: "community",
    operator: "TapeOut Index (community)",
    url: "https://tapeoutindex.lol/",
    original_language: "en",
    reviewed_at: "2026-08-31T00:00:00Z",
    title_en: "TapeOut Index",
    title_zh: "TapeOut Index 生态导航",
    summary_en: "Community-built link directory pointing to official pages and third-party TapeOut tools in one place. Reposted approvingly by protocol founder @Blonskr. Purely a navigation surface — it does not itself present price, holder or performance data.",
    summary_zh: "社区自建的链接导航站，把官方页面和第三方 TapeOut 工具汇总在一处。协议创始人 @Blonskr 曾转发致意。纯导航性质，本身不呈现价格、持仓或收益数据。",
    use_cases: ["navigation", "discovery"],
    safety_en: "Community directory, not an official source. No wallet-connect, signature or transaction prompt was found on the page during review; it only links out. Verify any linked tool independently before connecting a wallet there.",
    safety_zh: "社区导航站，非官方来源。审核时页面未发现钱包连接、签名或交易请求，仅做外部链接跳转。跳转到任何被链接的工具前应独立核实。"
  },
  {
    id: "tool-tg-official-group",
    wallet_risk: "read_only",
    category: "community_news",
    tier: "official",
    operator: "TapeOut Protocol (linked by founder @Blonskr)",
    url: "https://t.me/TapeOutnet",
    original_language: "en",
    reviewed_at: "2026-09-01T17:40:00Z",
    title_en: "TapeOut official Telegram group",
    title_zh: "TapeOut 官方 Telegram 群",
    summary_en: "The Telegram group carried in protocol founder @Blonskr's own X profile. Catalogued on that evidence: this directory already treats his publications as an official-tier source, so a channel he links from his own profile is corroborated to the same standard.",
    summary_zh: "协议创始人 @Blonskr 在其 X 个人简介中挂出的 Telegram 群。收录依据即此：本目录本就把他本人的发布当作官方级来源，那么他从自己简介里链出的频道，佐证强度属于同一档。",
    use_cases: ["announcements", "community-chat"],
    safety_en: "Read the evidence for and against before trusting this as official. For: the founder's own X profile links it. Against: tapeout.net itself publishes no social links whatsoever — not Telegram, X, Discord or GitHub — so the protocol's own site offers nothing to check it against, and a reader who trusts only the official website has no confirmation here. A group name resembling the protocol's is never itself evidence. Whatever its status, the standing rule holds inside any chat: the project does not DM you to design or tape out on your behalf, and a contract address posted in a chat must be matched against the official site before you sign anything.",
    safety_zh: "把支持与反对的证据都读完再决定是否当作官方。支持：创始人本人的 X 简介链接了它。反对：tapeout.net 官网**完全不公布任何社交链接**——没有 Telegram、X、Discord 或 GitHub——所以协议自己的站点无法为它提供任何佐证；只信任官网的读者在这里得不到确认。群名与协议相似本身绝不构成证据。无论其身份如何，聊天群内的通行规则不变：项目方不会私信替你设计或代你流片；任何在聊天中出现的合约地址，签名前必须先与官网核对。"
  },
  {
    id: "tool-tg-large-trade-alerts",
    wallet_risk: "read_only",
    category: "community_news",
    tier: "community",
    operator: "community-run Telegram channel",
    url: "https://t.me/TapeOutProtocol",
    original_language: "zh",
    reviewed_at: "2026-08-31T09:30:00Z",
    title_en: "Large-trade alert channel (community Telegram)",
    title_zh: "大额成交提醒频道（社区 Telegram）",
    summary_en: "A community-run Telegram channel that pushes TapeOut-related updates, circulated in community lists as a large-trade detection feed. Its own channel description states plainly that it is an unofficial channel built and maintained by community users.",
    summary_zh: "社区自建的 Telegram 频道，推送 TapeOut 相关内容，在社区清单中被作为「大单成交检测」渠道流传。该频道自己的简介明确写明是由社区用户自建维护的非官方频道。",
    use_cases: ["trade-alerts", "community-feed"],
    safety_en: "Explicitly self-declared as UNOFFICIAL despite its channel name resembling the protocol's. A channel name is never proof of affiliation. Alerts are one community member's own detection setup with undisclosed thresholds and no accuracy guarantee — never treat a push message as a verified fact, a protocol announcement or a trading signal, and never act on a contract address posted in any chat without checking it against the official site first.",
    safety_zh: "尽管频道名称与协议同名，但其**自己声明为非官方频道**。频道名称绝不构成从属关系的证明。提醒内容是某位社区成员自建的检测方案，阈值未公开、准确性无保证——不要把推送消息当作已核实的事实、官方公告或交易信号；任何在聊天群里出现的合约地址，都必须先与官网核对后才能使用。"
  },
  {
    id: "tool-tapeout-daily",
    drift_profile: "structure", // a newsroom's headings are its content; only its title/nav are product structure
    wallet_risk: "read_only",
    category: "community_news",
    tier: "community",
    operator: "@CryptoLoser9 (community)",
    url: "https://tapeoutdaily.ai/",
    original_language: "zh",
    reviewed_at: "2026-09-02T01:15:00Z",
    title_en: "TapeOut Daily community newsroom",
    title_zh: "TapeOut Daily 社区日报",
    summary_en: "Unofficial community newsroom whose front page has matured into a verification-first layout: a lead story labelled with its source tier and its own verification timestamp, on-chain supply snapshots stamped with the time of record and linked back to the original source, and — replacing the earlier KOL-engagement ranking — a rolling 36-hour community-post feed where each post carries a signal score, a source-tier label (founder post, community analysis, or awaiting official confirmation) and a per-post verification time. It states its own editorial rule that when little qualifies it shows little, rather than passing off older posts as current. Still offers the learning path, curated videos and tool index, and explicitly disclaims investment advice.",
    summary_zh: "非官方社区日报，首页已经长成一个核验优先的版式：头条新闻标注来源分级和独立的核验时间戳；链上供给快照记录发布时点并回链原始来源；原先的 KOL 活跃度榜单已演化为滚动的「36 小时社区原帖流」——每条原帖带信号分、来源分级（创始人原帖/社区分析/待官方核对）和逐条核验时间。它明文写出自己的编辑规则：合格内容少就少展示，不拿旧帖冒充最新。教学路径、精选视频与工具索引仍在，并明确声明不构成投资建议。",
    use_cases: ["community-news", "kol-tracking", "discovery"],
    safety_en: "Community editorial product, not an official source. No wallet-connect was found on the page during review — it only links out, to a Telegram channel and to third-party tools. Treat any ranking, price snapshot or curated claim as this site's own editorial judgment, cross-check against primary sources before acting.",
    safety_zh: "社区编辑类产品，非官方来源。审核时页面未发现钱包连接功能，仅链接到 Telegram 频道与第三方工具。任何榜单、价格快照或推荐内容都应视为该站自己的编辑判断，行动前请与一手来源交叉核实。"
  }
]);
