// TapeOut glossary seed. Every definition summarizes publicly displayed
// official material (tapeout.net and its PoD pages) — no invented mechanics,
// no return language, no identity inference. Definitions are descriptive,
// not normative: the official site remains the only rule source.
export const GLOSSARY_VERSION = "2026-08-27-glossary-r1";
export const GLOSSARY_REVIEWED_AT = "2026-08-27";

export const GLOSSARY = Object.freeze([
  { id: "processor", term_en: "Processor", term_zh: "处理器", def_en: "A project unit on TapeOut. Each Processor pairs a public circuit registry contract with its own Transistor token, and appears in the public Registry with a name, creator address, declared supply and observed circuit count.", def_zh: "TapeOut 上的项目单元。每个处理器由一个公开电路注册合约和其专属晶体管代币组成，在公开 Registry 中带有名称、创建者地址、声明供给量与已观察电路数。", evidence_url: "https://tapeout.net/" },
  { id: "transistor", term_en: "Transistor (NAND / LATCH)", term_zh: "晶体管（NAND / LATCH）", def_en: "The component tokens of a Processor. NAND is the combinational primitive and LATCH the stateful primitive; taping out a circuit burns them from the author's balance.", def_zh: "处理器的元件代币。NAND 是组合逻辑原语，LATCH 是状态原语；流片电路时会从作者余额中燃烧对应数量。", evidence_url: "https://tapeout.net/" },
  { id: "circuit", term_en: "Circuit", term_zh: "电路", def_en: "An on-chain netlist published onto a Processor. Circuits are executable through public read-only calls and are counted per Processor in the Registry.", def_zh: "发布到处理器上的链上网表。电路可通过公开只读调用执行，并按处理器计入 Registry 的电路数。", evidence_url: "https://tapeout.net/" },
  { id: "tapeout", term_en: "Tape-out", term_zh: "流片", def_en: "The act of publishing a netlist on-chain. The submission burns the circuit's NAND/LATCH from the author and mints the circuit record.", def_zh: "把网表发布上链的动作。提交时按网表构成燃烧作者的 NAND/LATCH，并铸出电路记录。", evidence_url: "https://tapeout.net/" },
  { id: "mint", term_en: "Mint", term_zh: "铸造", def_en: "Purchasing Transistors from a Processor at its configured mint price, up to the declared supply cap.", def_zh: "按处理器配置的铸造价格购入晶体管，上限为声明供给量。", evidence_url: "https://tapeout.net/" },
  { id: "supply-cap", term_en: "Supply cap", term_zh: "声明供给", def_en: "The maximum Transistor supply a Processor declares. This monitor groups Processors by observed supply-cap bands without inferring intent.", def_zh: "处理器声明的晶体管供给上限。本站按观察到的供给档位分组，不推断项目意图。", evidence_url: "https://tapeout.net/" },
  { id: "mint-completion", term_en: "Mint completion", term_zh: "铸造完成度", def_en: "Observed minted units divided by declared supply cap. A display measure computed from public Registry values only.", def_zh: "已观察铸造量除以声明供给量，仅由公开 Registry 数值计算的展示指标。", evidence_url: "https://tapeout.net/" },
  { id: "pod", term_en: "Proof of Design (PoD)", term_zh: "设计证明（PoD）", def_en: "The $BEM mining mechanism: verified circuit designs submitted against the official taskbank earn a share of daily emission according to their published scoring weight.", def_zh: "$BEM 的挖矿机制：对照官方题库提交并通过验证的电路设计，按公开评分权重分享每日产出。", evidence_url: "https://tapeout.net/pod/" },
  { id: "bem", term_en: "$BEM", term_zh: "$BEM", def_en: "The PoD reward token. Daily emission is split across qualifying circuits by weight; third-party market prices for $BEM are not official protocol prices.", def_zh: "PoD 的奖励代币。每日产出按权重在合格电路间分配；第三方行情价格不是协议官方价格。", evidence_url: "https://tapeout.net/pod/" },
  { id: "taskbank", term_en: "Taskbank", term_zh: "题库", def_en: "The official catalog of reference design tasks. Each task publishes reference gates, depth and C_ref, plus on-chain eligibility limits.", def_zh: "官方参考设计任务目录。每道题公开参考门数、深度与 C_ref，以及可上链的资格限制。", evidence_url: "https://tapeout.net/pod/" },
  { id: "gates-depth", term_en: "Gate count / depth", term_zh: "门数 / 深度", def_en: "Size and timing measures of a netlist: total elements, and the longest combinational path. The official scoring cubes depth, so depth reductions matter far more than element count.", def_zh: "网表的规模与时延指标：元件总数与最长组合路径。官方评分对深度取三次方，因此降低深度远比减少门数值钱。", evidence_url: "https://tapeout.net/pod/" },
  { id: "c-cref", term_en: "C and C_ref", term_zh: "C 与 C_ref", def_en: "C = A × max(d,1)³ where A counts elements (LATCH weighted ×6) and d is depth. C_ref is the official reference implementation's C for the same task.", def_zh: "C = A × max(d,1)³，其中 A 为元件计数（LATCH 权重 ×6），d 为深度。C_ref 是同一题官方参考实现的 C。", evidence_url: "https://tapeout.net/pod/" },
  { id: "q", term_en: "q (quality multiplier)", term_zh: "q（质量系数）", def_en: "q = clamp(C_ref / C, 1/4, 4). Designs better than the reference earn up to 4×; worse designs floor at 1/4. Only the current best original holder of a task earns the q-scaled bonus.", def_zh: "q = clamp(C_ref / C, 1/4, 4)。优于参考实现最高得 4 倍，劣于参考实现下限 1/4；只有该题当前最优首创持有者能获得 q 加成。", evidence_url: "https://tapeout.net/pod/" },
  { id: "h-weight", term_en: "H (mining weight)", term_zh: "H（挖矿权重）", def_en: "H = (b* + K_task · q) × P, where b* is the submission's burned transistors, K_task the reference implementation's own b*, and P the processor multiplier. Daily $BEM share is proportional to H.", def_zh: "H = (b* + K_task · q) × P。b* 为本次提交燃烧的晶体管数，K_task 为该题参考实现自身的 b*，P 为处理器系数。每日 $BEM 按 H 占比分配。", evidence_url: "https://tapeout.net/pod/" },
  { id: "p-multiplier", term_en: "P (processor multiplier)", term_zh: "P（处理器系数）", def_en: "The per-processor coefficient on the official mining list. Only listed processors qualify for PoD weight.", def_zh: "官方挖矿名单中按处理器给定的系数；只有名单内的处理器才具备 PoD 权重资格。", evidence_url: "https://tapeout.net/pod/" },
  { id: "ref", term_en: "REF (circuit reference)", term_zh: "REF（电路引用）", def_en: "Referencing an existing circuit inside a new netlist. Under the published PoD rules, netlists must be REF-free to carry mining weight.", def_zh: "在新网表中引用已有电路。按已公开的 PoD 规则，网表必须零 REF 才具备挖矿权重。", evidence_url: "https://tapeout.net/pod/" },
  { id: "airdrop", term_en: "Airdrop", term_zh: "空投", def_en: "The public TapeOut airdrop contract distributing per-claim Transistor allocations from creator-funded pools. Its raw units are separate from Registry mint totals.", def_zh: "TapeOut 公开空投合约，从创建者注资的池中按次分发晶体管。其原始单位与 Registry 铸造总量相互独立。", evidence_url: "https://tapeout.net/#airdrop" },
  { id: "creator", term_en: "Creator", term_zh: "创建者", def_en: "The public Registry's creator address field for a Processor. It identifies a deploying address only — not an off-chain identity or a project's full wallet set.", def_zh: "公开 Registry 中处理器的创建者地址字段。它只标识部署地址，不代表链下身份或项目全部关联钱包。", evidence_url: "https://tapeout.net/" },
]);
