// Curated learning catalog: every entry was reviewed against the public-source
// governance note. Community entries never inherit official status; references
// explain digital-logic concepts only and are not TapeOut Protocol tutorials.
export const LEARNING_CATALOG_VERSION = "2026-08-31";
export const LEARNING_CATALOG_REVIEWED_AT = "2026-08-31T00:00:00Z";
export const LEARNING_RESOURCES = Object.freeze([
  { id: "official-home", tier: "official", stages: ["basics", "canvas", "tapeout"], language: ["zh", "en"], title_zh: "TapeOut 官网：从 NAND/LATCH 到链上 Circuit", title_en: "TapeOut official site: from NAND/LATCH to on-chain Circuits", summary_zh: "从元件、Processor 与 Canvas 开始，先理解流片后会消耗元件并生成链上 Circuit；也披露当前合约仍可升级。", summary_en: "Start with components, Processors and Canvas; tape-out consumes components and creates an on-chain Circuit. The site also discloses that contracts remain upgradeable.", url: "https://tapeout.net/" },
  { id: "official-whitepaper", tier: "official", stages: ["basics", "tapeout"], language: ["zh"], title_zh: "TapeOut Protocol 白皮书", title_en: "TapeOut Protocol whitepaper", summary_zh: "解释晶体管 ERC-1155、电路 ERC-721、处理器工厂与链上网表，是术语和协议结构的官方参考。", summary_en: "Official reference for ERC-1155 components, ERC-721 Circuits, the Processor factory and on-chain netlists.", url: "https://tapeout.net/TapeOut-Protocol.pdf" },
  { id: "official-alpha", tier: "official", stages: ["basics", "canvas"], language: ["zh", "en"], title_zh: "Alpha 上线演示：画布、流片与示例规模", title_en: "Alpha launch demo: Canvas, tape-out and examples", summary_zh: "项目公开发布中用 NAND、LATCH、画布连线和处理器示例说明从设计到流片的基本路径。", summary_en: "Official launch post demonstrating the basic path from NAND/LATCH and Canvas wiring to tape-out.", url: "https://x.com/Blonskr/status/2088639148660076696" },
  { id: "official-output-cost", tier: "official", stages: ["canvas", "tapeout"], language: ["zh", "en"], title_zh: "输出引脚成本与网表规则说明", title_en: "Output-pin cost and netlist rule note", summary_zh: "解释为什么 Canvas 上的门数不一定等于最终流片消耗，适合在签名前核对输入、输出与成本。", summary_en: "Explains why Canvas gate count may differ from final tape-out consumption; useful before checking inputs, outputs and cost.", url: "https://x.com/Blonskr/status/2090510180979278026" },
  { id: "community-market-qa", tier: "community", stages: ["safety"], language: ["en"], title_zh: "TapeOut Market Q&A：订单、费用与签名安全", title_en: "TapeOut Market Q&A: orders, fees and signing safety", summary_zh: "社区编写的买单 BNB 托管、显示的买方费用、Gas 与签名安全说明；美元估值不等于保证售价，平台不应索取私钥或助记词。", summary_en: "Community-written explanation of escrowed BNB buy orders, displayed buyer fees, gas and signing safety; USD estimates do not guarantee execution or a sale price, and no platform should request a private key or seed phrase.", url: "https://tapeout.market/qa" },
  { id: "official-pod", tier: "official", stages: ["pod", "safety"], language: ["zh", "en"], title_zh: "$BEM Proof of Design：官方挖矿入口", title_en: "$BEM Proof of Design: official mining entry", summary_zh: "进入 arm / start / claim、题库与官方合约入口；页面明确交易不可逆、无需买币、早期流动性较浅。", summary_en: "Official entry for arm / start / claim, taskbank and contracts; it states transactions are irreversible, buying tokens is not required and early liquidity may be thin.", url: "https://tapeout.net/pod/" },
  { id: "official-pod-tasks", tier: "official", stages: ["pod"], language: ["zh", "en"], title_zh: "PoD 题库：从可上链题目开始", title_en: "PoD taskbank: start with eligible tasks", summary_zh: "官网题库入口。先按难度、组合/时序与上链资格挑选练习题，再阅读官方验证要求。", summary_en: "Official taskbank entry. Choose by tier, combinational/sequential type and on-chain eligibility before studying verification requirements.", url: "https://tapeout.net/pod/#pod-tasks" },
  { id: "official-pod-algo", tier: "official", stages: ["pod"], language: ["zh", "en"], title_zh: "PoD 算法：资格、验证与公式", title_en: "PoD algorithm: eligibility, verification and formulas", summary_zh: "解释公开成本、资格、认领和验证规则；这些公式用于规则理解，不预测挖矿回报。", summary_en: "Explains public cost, eligibility, claim and verification rules; formulas explain rules and do not forecast mining returns.", url: "https://tapeout.net/pod/#pod-algo" },
  { id: "community-first-tapeout", tier: "community", stages: ["canvas", "tapeout", "safety"], language: ["en"], title_zh: "社区新手路径：从 Mint 到 Tape-Out", title_en: "Community beginner path: from Mint to Tape-Out", summary_zh: "以小额隔离钱包、画布测试、签名核验和不可逆流片为线索的社区教程；机制应以官网为准。", summary_en: "Community guide emphasizing an isolated small wallet, Canvas tests, signature checks and irreversible tape-out; official sources remain authoritative for mechanics.", url: "https://www.htx.com/es-la/news/from-minting-to-tape-out-a-first-timers-guide-to-tapeout-kqsyMu7c/" },
  { id: "community-cn-logic", tier: "community", stages: ["canvas", "logic"], language: ["zh"], title_zh: "中文练习阶梯：从 NOT/AND/XOR 到加法器", title_en: "Chinese practice ladder: NOT/AND/XOR to adders", summary_zh: "社区长文提供由基础门到加法器的练习顺序；仅将可与官网核验的电路机制用作参考，不采纳其中市场观点。", summary_en: "Community ladder from basic gates to adders. Only mechanism descriptions cross-checkable with official sources are used; market views are not adopted.", url: "https://x.com/blackshixin/article/2089327095793229941" },
  { id: "community-something-logic-intro", tier: "community", stages: ["basics", "logic", "canvas", "safety"], language: ["zh"], title_zh: "社区机制入门：从 NAND/LATCH 到流片与 PoD", title_en: "Community mechanism primer: NAND/LATCH, tape-out and PoD", summary_zh: "Something Labs 的中文社区科普从 NAND、LATCH 与链上 Circuit 出发，介绍流片、测试向量和 PoD 的基本词汇。官网仍是规则与合约的唯一权威来源；不采纳文中的买入、囤积、挖矿或价格观点。", summary_en: "A Chinese community primer by Something Labs introduces NAND, LATCH, on-chain Circuits, tape-out, test vectors and PoD vocabulary. Official sources remain authoritative for rules and contracts; buying, holding, mining and price commentary in the post are not adopted.", url: "https://x.com/something_labs/status/2092151538898858138" },
  { id: "community-93bitmap-video-intro", tier: "community", stages: ["basics", "logic"], language: ["en"], title_zh: "社区英文视频：TapeOut 科普第一集", title_en: "Community video: TapeOut science primer · episode 1", summary_zh: "93.bitmap 发布的英文科普视频，以 TapeOut 与 Ordinals 的对照作为概念入口。仅作社区视频参考，不代表官网规则、合约、价格、收益或市场判断。", summary_en: "An English community explainer video by 93.bitmap that uses TapeOut and Ordinals as a conceptual entry point. It is a community video reference only, not an official source for rules, contracts, prices, returns or market claims.", url: "https://x.com/93bitmap/status/2092453478530691106" },
  { id: "community-93bitmap-video-ep2", tier: "community", stages: ["basics", "logic"], language: ["en"], title_zh: "社区英文视频：TapeOut 科普第二集", title_en: "Community video: TapeOut science primer · episode 2", summary_zh: "93.bitmap 科普系列的第二集，英文版视频概念入门。仅作社区视频参考，不代表官网规则、合约、价格、收益或市场判断，帖子正文未提供可核验的技术材料。", summary_en: "The second episode of 93.bitmap's explainer series, an English-language conceptual primer. It is a community video reference only, not an official source for rules, contracts, prices, returns or market claims; the post text itself provides no independently verifiable technical material.", url: "https://x.com/93bitmap/status/2092851708384964682" },
  { id: "community-93bitmap-video-ep3", tier: "community", stages: ["basics", "logic"], language: ["zh"], title_zh: "社区中文视频：科普第三集·为什么 TapeOut 不是打金链游", title_en: "Community video: TapeOut science primer · episode 3 (why it isn't a play-to-earn chain game)", summary_zh: "93.bitmap 科普系列第三集，从概念上说明 TapeOut 与传统打金链游的区别。仅作社区视频参考，不代表官网规则、合约、价格、收益或市场判断，帖子正文未提供可核验的技术材料。", summary_en: "The third episode of 93.bitmap's explainer series, framing conceptually why TapeOut differs from a typical play-to-earn chain game. It is a community video reference only, not an official source for rules, contracts, prices, returns or market claims; the post text itself provides no independently verifiable technical material.", url: "https://x.com/93bitmap/status/2092861107757351243" },
  { id: "reference-sr-latch", tier: "reference", stages: ["logic"], language: ["en"], title_zh: "概念参考：NAND SR Latch", title_en: "Concept reference: NAND SR latch", summary_zh: "用真值表和门级图解释 SR latch；这是数字逻辑材料，不是 TapeOut Protocol 的操作教程。", summary_en: "Explains the SR latch using truth tables and gate diagrams. This is digital-logic reference material, not a TapeOut Protocol operating guide.", url: "https://www.bristolwatch.com/ele3/nand_sr_latch.htm" },
  { id: "reference-bscscan-pod", tier: "reference", stages: ["safety", "pod"], language: ["en"], title_zh: "只读核验：PoD 合约浏览器入口", title_en: "Read-only verification: PoD contract explorer", summary_zh: "通过区块浏览器核对官网公开的 PoD 合约地址与交易状态；不是审计结论，也不构成收益依据。", summary_en: "Use the block explorer to cross-check the public PoD contract address and transaction status; it is neither an audit conclusion nor a return metric.", url: "https://bscscan.com/address/0x7E2E0DC66a3bD9103E69b766afA62d9f7b697b46" },
  { id: "community-93bitmap-video-ep5-zh", tier: "community", stages: ["pod", "logic"], language: ["zh"], title_zh: "社区中文视频：科普第五集·tape 的角斗场范式转移", title_en: "Community video: TapeOut science primer · episode 5 (arena paradigm shift)", summary_zh: "93.bitmap 科普系列第五集，据作者所述是与创始人 @Blonskr 交流后修正的内容，围绕 V2 讨论中的\"开发者插槽\"与题目竞争机制的范式转移展开。仅作社区视频参考，不代表官网已正式公开发布的规则，V2 特性以官网未来正式公告为准。", summary_en: "The fifth episode of 93.bitmap's explainer series; per the author, revised after a conversation with founder @Blonskr, covering a discussed V2 \"developer slot\" concept and a paradigm shift in task competition. It is a community video reference only, not an officially published rule — any V2 feature remains subject to the official site's own future announcement.", url: "https://x.com/93bitmap/status/2093540774495531158" },
  { id: "community-93bitmap-video-ep5-en", tier: "community", stages: ["pod", "logic"], language: ["en"], title_zh: "社区英文视频：科普第五集（英文版）", title_en: "Community video: TapeOut science primer · episode 5 (English)", summary_zh: "93.bitmap 科普系列第五集的英文配音版本，内容与中文版一致。仅作社区视频参考，不代表官网规则，V2 特性以官网未来正式公告为准。", summary_en: "The English-dubbed version of episode 5, same content as the Chinese original. It is a community video reference only, not an official source for rules; any V2 feature remains subject to the official site's own future announcement.", url: "https://x.com/93bitmap/status/2093704731021685205" },
  { id: "community-93bitmap-scam-guide", tier: "community", stages: ["safety"], language: ["zh"], title_zh: "社区防骗要点：TapeOut 新手必读", title_en: "Community safety guide: TapeOut scam-pattern checklist for newcomers", summary_zh: "93.bitmap 整理的简明防骗清单：官方从不私信代设计/代流片，第三方工具应只用小额钱包且限额可撤销 approve，警惕仿盘代币/NFT 与\"先把零件打给我\"话术。发布后获创始人 @Blonskr 转发致谢。仅作社区安全提示参考，不替代独立核验每一笔签名请求。", summary_en: "A concise anti-scam checklist compiled by 93.bitmap: the official project never DMs to design or tape out on your behalf, third-party tools should only ever get a capped, revocable approve from a small wallet, and copycat tokens/NFTs plus \"send me the parts first\" pitches are common scam patterns. Reposted with thanks by founder @Blonskr. A community safety reference only — it does not replace independently verifying every signing request yourself.", url: "https://x.com/93bitmap/status/2093276579761897980" },
  { id: "community-93bitmap-video-ep6", tier: "community", stages: ["pod", "logic"], language: ["zh"], title_zh: "社区中文视频：科普第六集·虚拟工厂对现实有没有用", title_en: "Community video: TapeOut science primer · episode 6 (does the virtual factory matter)", summary_zh: "93.bitmap 科普系列第六集，围绕即将讨论的 V2 芯片设计虚拟工厂概念，阐述作者本人对其价值定位的理解，并以台积电订单模式作类比。这是作者的个人观点性论述，不是官网已发布规则；V2 具体机制以官网未来正式公告为准，不采纳文中的价值/收益类比。", summary_en: "The sixth episode of 93.bitmap's explainer series, discussing an upcoming V2 concept of a virtual chip-design factory and the author's own framing of its value, drawing an analogy to TSMC's order model. This is the author's personal opinion, not an officially published rule; any V2 mechanic remains subject to the official site's own future announcement, and the value/return analogy in the video is not adopted.", url: "https://x.com/93bitmap/status/2093902139622056167" },
]);
